# Generated by Django 3.0.1 on 2019-12-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario_ofertas_recebida', models.IntegerField(null=True)),
                ('id_usuario_ofertas_enviada', models.IntegerField(null=True)),
                ('id_item_oferta_recebida', models.IntegerField(null=True)),
                ('id_item_oferta_enviada', models.IntegerField(null=True)),
                ('data_da_oferta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
