# Generated by Django 3.0.1 on 2019-12-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Lances',
        ),
    ]
