# Generated by Django 3.0.1 on 2019-12-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incluir_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=200)),
                ('id_usuario_item_id', models.IntegerField()),
                ('dataConta', models.DateTimeField(auto_now_add=True)),
                ('imagem1', models.ImageField(upload_to='static/img/produtos')),
                ('imagem2', models.ImageField(upload_to='static/img/produtos')),
                ('imagem3', models.ImageField(upload_to='static/img/produtos')),
                ('imagem4', models.ImageField(upload_to='static/img/produtos')),
                ('imagem5', models.ImageField(upload_to='static/img/produtos')),
                ('visualizado', models.IntegerField(default=0, null=True)),
                ('categorias', models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Automóvel', 'Automóvel'), ('Mobiliarios', 'Mobiliarios'), ('Imovel', 'Imovel'), ('Animais', 'Animais'), ('Beleza', 'Beleza'), ('Moda', 'Moda'), ('Esporte', 'Esporte'), ('Brinquedo', 'Brinquedo'), ('Jóias e relógios', 'Jóias e relógios'), ('Ferramentas e Indústria', 'Ferramentas e Indústria'), ('Supermercado', 'Supermercado')], max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
