# Generated by Django 3.0.1 on 2019-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0016_auto_20191220_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incluir_item',
            name='id_usuario_item_id',
            field=models.IntegerField(null=True),
        ),
    ]
