# Generated by Django 3.0.1 on 2020-01-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0020_auto_20191228_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incluir_item',
            name='imagem1',
            field=models.ImageField(upload_to='static/img/produtos/'),
        ),
        migrations.AlterField(
            model_name='incluir_item',
            name='imagem2',
            field=models.ImageField(upload_to='static/img/produtos/'),
        ),
        migrations.AlterField(
            model_name='incluir_item',
            name='imagem3',
            field=models.ImageField(upload_to='static/img/produtos/'),
        ),
        migrations.AlterField(
            model_name='incluir_item',
            name='imagem4',
            field=models.ImageField(upload_to='static/img/produtos/'),
        ),
        migrations.AlterField(
            model_name='incluir_item',
            name='imagem5',
            field=models.ImageField(upload_to='static/img/produtos/'),
        ),
    ]
